# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: chatqna
description: The Helm chart to deploy ChatQnA
type: application
dependencies:
  - name: tgi
    version: 1.2.0
    alias: tgi-guardrails
    repository: "file://../common/tgi"
    condition: tgi-guardrails.enabled
  - name: guardrails-usvc
    version: 1.2.0
    repository: "file://../common/guardrails-usvc"
    condition: guardrails-usvc.enabled
  - name: tgi
    version: 1.2.0
    repository: "file://../common/tgi"
    condition: tgi.enabled
  - name: vllm
    version: 1.2.0
    repository: "file://../common/vllm"
    condition: vllm.enabled
  - name: llm-uservice
    version: 1.2.0
    repository: "file://../common/llm-uservice"
    condition: llm-uservice.enabled
  - name: tei
    version: 1.2.0
    repository: "file://../common/tei"
  - name: embedding-usvc
    version: 1.2.0
    repository: "file://../common/embedding-usvc"
    condition: embedding-usvc.enabled
  - name: teirerank
    version: 1.2.0
    repository: "file://../common/teirerank"
    condition: teirerank.enabled
  - name: reranking-usvc
    version: 1.2.0
    repository: "file://../common/reranking-usvc"
    condition: reranking-usvc.enabled
  - name: redis-vector-db
    version: 1.2.0
    repository: "file://../common/redis-vector-db"
    condition: redis-vector-db.enabled
  - name: retriever-usvc
    version: 1.2.0
    repository: "file://../common/retriever-usvc"
  - name: data-prep
    version: 1.2.0
    repository: "file://../common/data-prep"
  - name: ui
    alias: chatqna-ui
    version: 1.2.0
    repository: "file://../common/ui"
  - name: nginx
    version: 1.2.0
    repository: "file://../common/nginx"
version: 1.2.0
appVersion: "v1.0"
