# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: audioqna
description: The Helm chart to deploy AudioQnA
type: application
dependencies:
  - name: whisper
    version: 1.2.0
    repository: "file://../common/whisper"
  - name: speecht5
    version: 1.2.0
    repository: "file://../common/speecht5"
  - name: tgi
    version: 1.2.0
    repository: "file://../common/tgi"
  - name: ui
    version: 1.2.0
    repository: "file://../common/ui"
    alias: audioqna-ui
  - name: nginx
    version: 1.2.0
    repository: "file://../common/nginx"
version: 1.2.0
appVersion: "1.1"
